[phases.setup]
nixPkgs = ["python311", "nodejs_18", "npm"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "cd frontend && npm install"
]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "python start_railway.py" 