[build]
builder = "heroku/buildpacks:20"
buildpacks = ["heroku/python"]

[deploy]
startCommand = "cd backend && python -m uvicorn main_deploy:app --host 0.0.0.0 --port $PORT"

[variables]
PYTHONPATH = "backend" 